### ISSUE TITLE
Convert emojis to text smileys

### ISSUE THREAD

**Issue by ekmartin** [ekmartin/slack-irc#10]
Could convert emojis to regular text smileys, i.e. from `:smile:` to `:)`.

**Comment by matschaffer** [comment]
Converting to utf8 (e.g., 😄) could be good given that the base slack set is utf8 based.

**Comment by ekmartin** [comment]
Could be a good idea, but I don't think IRC clients like WeeChat/irssi support utf-8 emojis without plugins, which will make them show up like empty spaces.

**Comment by matschaffer** [comment]
Ah, fair point. I've been on Colloquy so long I just assume. Glad you have some additional context.
