### ISSUE TITLE
No way to set server password

### ISSUE THREAD

**Issue by RoboMWM** [ekmartin/slack-irc#106]
Seems there's no way to set the server password.

I'm connecting this to a ZNC hence the need for this.

**Comment by ekmartin** [comment]
Hi! You can add an `ircOptions` object to your config, which is then passed directly to [node-irc](https://node-irc.readthedocs.org/en/latest/API.html#client).
Setting password and userName here should do it:

```json
[{
  ...rest of your config,
  "ircOptions": {
    "userName": "twitch-username",
    "password": "oauth:token-goes-here"
  }
}]
```

If you need SASL support you can add `"sasl": true`.
Let me know if it doesn't work out, and I'll reopen the issue.

**Comment by RoboMWM** [comment]
Um, is this the nickserv password field? I tried this and had the same error. I need to input a server password, not nickserv password.

**Comment by RoboMWM** [comment]
Double-checked that I tried the password field, unfortunately no difference though, since I'm sure that password field is for nickserv/sasl authentication, not IRC server password.

```powershell
error: Received error event from IRC prefix=irc.znc.in, server=irc.znc.in, command=err_passwdmismatch, rawCommand=464, c
ommandType=error, args=[zncusernamehere, Password required]
13 Apr 18:08:59 - ERROR: { prefix: 'irc.znc.in',
  server: 'irc.znc.in',
  command: 'err_passwdmismatch',
  rawCommand: '464',
  commandType: 'error',
  args: [ 'zncusernamehere', 'Password required' ] }

**Comment by Someguy123** [comment]
@ekmartin This doesn't work over here, nor for @RoboMWM - seemingly I can't even get it to work for SASL either (works fine from any normal client). Using chat.freenode.net:6697 with secure:true

**Comment by ekmartin** [comment]
@RoboMWM got it working by removing the SASL option.
>I guess when I was playing around with different ircOptions in attempts to get it to work I added the sasl option. Removing that seems to work now.

I.e. for server password:

```json
"ircOptions": {
  "userName": "user",
  "password": "password"
}
```

for SASL you should be able to do the same, but with the sasl option added:
```json
"ircOptions": {
  "userName": "user",
  "password": "password",
  "sasl": true
}
```

**Comment by Someguy123** [comment]
@ekmartin Tried that, it doesn't seem to work at all. Adding a password (tried SASL, as well as plain password, and password = user:password) makes it just stick on this:

    debug: Connecting to IRC and Slack
    debug: Connected to Slack

It seems to still get the Slack messages while stuck here, but it doesn't connect to the network, which I can confirm from my actual IRC client

**Comment by RoboMWM** [comment]
@Someguy123 This was regarding server password, not nickserv password. I'd assume there's a separate option for that, but then again I haven't looked into it thoroughly.

For background, I was trying different options when it didn't work for me initially. I think I also had other issues when trying to fix this issue, and thus had added extra options when this was the final issue to take care of.

**Comment by Someguy123** [comment]
@RoboMWM I'm not talking about NickServ password either. I'm talking about freenode's server password auth (in other IRC bots, I set the server password to username:password to auth before connection, preventing IP leak).

Seems I can't get this to work, even with SASL (but it works fine in other IRC bots, and IRC clients)

**Comment by Someguy123** [comment]
Hmmm, now this is odd. It looks like the real culprit was `"secure": true`

I don't even understand how, because 6697 is an SSL port, and it somehow connects fine without secure...

**Comment by RoboMWM** [comment]
Hmm, not sure how freenode's server password auth works as I don't use it, but here's a snippet of my config:
```json
"ircOptions": {
	  "secure": true,
	  "showErrors": true,
	  "selfSigned": true,
	  "certExpired": true
    }

**Comment by Someguy123** [comment]
UPDATE: actually it looks like it's not connecting to freenode via SSL like I thought. Activity monitor shows it's on 6667... *sigh*

**Comment by RoboMWM** [comment]
Ah yea, I use port in options as well.
