### ISSUE TITLE
Æ ø å

### ISSUE THREAD

**Issue by lionleaf** [ekmartin/slack-irc#11]
The bot doesn't seem to support æ ø å :(  (or is incorrectly configured for Hackerspace's slack)

![ceqqdpv](https://cloud.githubusercontent.com/assets/610925/6583402/4fe00f6a-c73a-11e4-988e-0553c28d4dda.png)

**Comment by ekmartin** [comment]
Hm, seems to work for me (with WeeChat). The issue might be with your IRC client, which one are you using?

![image](https://cloud.githubusercontent.com/assets/3536982/6658146/d6e4ee98-cb60-11e4-9ea8-cc579335cf59.png)
