### ISSUE TITLE
fails to launch

### ISSUE THREAD

**Issue by andyseubert** [ekmartin/slack-irc#111]
This was working until a few minutes ago 
now I am receiving this error
npm ERR! Windows_NT 6.0.6002
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "sta
rt" "--config" "config.json"
npm ERR! node v4.4.2
npm ERR! npm  v2.15.0
npm ERR! code ELIFECYCLE
npm ERR! slack-irc@3.7.8 start: `node dist/index.js "config.json"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the slack-irc@3.7.8 start script 'node dist/index.js "config.json"'.
npm ERR! This is most likely a problem with the slack-irc package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node dist/index.js "config.json"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs slack-irc
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls slack-irc
npm ERR! There is likely additional logging output above.

Here is the debug log
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start',
1 verbose cli   '--config',
1 verbose cli   'config.json' ]
2 info using npm@2.15.0
3 info using node@v4.4.2
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart slack-irc@3.7.8
6 info start slack-irc@3.7.8
7 verbose unsafe-perm in lifecycle true
8 info slack-irc@3.7.8 Failed to exec start script
9 verbose stack Error: slack-irc@3.7.8 start: `node dist/index.js "config.json"`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:217:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:827:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid slack-irc@3.7.8
11 verbose cwd C:\Users\andys.EVIL_EMPIRE\AppData\Roaming\npm\node_modules\slack-irc
12 error Windows_NT 6.0.6002
13 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start" "--config" "config.json"
14 error node v4.4.2
15 error npm  v2.15.0
16 error code ELIFECYCLE
17 error slack-irc@3.7.8 start: `node dist/index.js "config.json"`
17 error Exit status 1
18 error Failed at the slack-irc@3.7.8 start script 'node dist/index.js "config.json"'.
18 error This is most likely a problem with the slack-irc package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     node dist/index.js "config.json"
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs slack-irc
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls slack-irc
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

**Comment by andyseubert** [comment]
.. aaand now it's working again.
not sure what fixed it nor what broke it.
I regenerated my slack bot key, and tried nmp update but I don't think either one fixed it.

**Comment by ekmartin** [comment]
Hm, hard to say. If it happens again you can export the environment variable `NODE_ENV` to `development` before running, to enable debug information.
