### ISSUE TITLE
IRC Username randomly changed

### ISSUE THREAD

**Issue by Someguy123** [ekmartin/slack-irc#118]
I have an IRC bridge from my slack channel to Freenode. After running for approximately 9 days, I found my bot with the name: `7YUAAYVY7`. It was still working, however I don't understand where it got this name from.

I checked the logs, unfortunately I don't have debug turned on, so there was nothing to tell me what happened.

I restarted the bot and the username is now correct.

Very strange bug, but needs to be fixed.

**Comment by ekmartin** [comment]
Sounds extremely strange, as there's no code in slack-irc that ever tries to do something like changing a nick. You're sure it wasn't because you used a NickServ registered nickname without authenticating? That would probably result in Freenode changing your nickname.

**Comment by Someguy123** [comment]
@ekmartin: AFAIK Freenode doesn't do random nick's like that, AND it was using auth-on-connect via server password. I could tell by the bots hostname that it was **fully authenticated**, so it can't have been NickServ changing it...

If Freenode changes your nick due to something like that, it would have become "Guest12345" etc.

**Comment by ekmartin** [comment]
Hm, weird. node-irc (the IRC library slack-irc uses) doesn't even have API support for changing nicks at runtime, you have to do it by manually sending a raw `NICK` command to the IRC server - which isn't done anywhere in the slack-irc or node-irc code base.

I'm going to close this, but would be nice if you could run your bot with NODE_ENV=development and report back if it happens again.
