### ISSUE TITLE
Msg only send one way 

### ISSUE THREAD

**Issue by dasTholo** [ekmartin/slack-irc#121]
I ve the problem that msg only send from irc to slack, but doesn´t send from slack to irc.
Did you have any solution?

**Comment by ekmartin** [comment]
Hi, are you running the latest version of slack-irc?
If you run the application with NODE_ENV=development you'll see a bit more debug logging, which might help you corner in on the issue.

**Comment by dasTholo** [comment]
Okay! I ve find the fail behind the monitor...
i´ve only write 
` "channelMapping": { // Maps each Slack-channel to an IRC-channel, used to direct messages to the correct place
      "test": "#test", // Add channel keys after the channel name
`
but it must be 
`      "#test": "#test", // Add channel keys after the channel name
`

sry my fail

**Comment by ekmartin** [comment]
Glad you got it working :)
