### ISSUE TITLE
Getting an error when I try to install it.

### ISSUE THREAD

**Issue by wcktklwn** [ekmartin/slack-irc#126]
npm ERR! 404 Not Found
npm ERR! 404
npm ERR! 404 'slack/client' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 It was specified as a dependency of 'slack-irc'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Linux 3.16.0-4-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "slack-irc"
npm ERR! cwd /home/bots
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code E404
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/bots/npm-debug.log
npm ERR! not ok code 0

**Comment by ekmartin** [comment]
Hi! Upgrade your npm version, it's really old. You need one that supports organizational namespaces, i.e. `@slack/client` :)

Instructions here: https://github.com/nodesource/distributions
