### ISSUE TITLE
PM/DMs

### ISSUE THREAD

**Issue by Oobert** [ekmartin/slack-irc#145]
Give the structure of this module and the slack API, is it possible to have Private/direct messages work? 

I ask it this way because I may have time to try but before I do, I want to know if you think it is possible first. 

Thank you,
Tony

**Comment by ekmartin** [comment]
It's definitely possible. However, when it came up on previous occasions it was usually because people wanted to use slack-irc as a personal IRC client from Slack, and for that I recommend https://github.com/aeirola/slack-irc-client instead. Do you have a different use case?

**Comment by Oobert** [comment]
Sorry for my delay in response. Life... 

I was testing out a workflow between slack and IRC with a group. It wasn't working out and PM/DMs wasn't the deal breaker.
