### ISSUE TITLE
emoji.json multiple checkins

### ISSUE THREAD

**Issue by iMartyn** [ekmartin/slack-irc#155]
Hi, I got very frustrated and confused because I wanted to add a mapping for :slightly_smiling_face:

I was adding it in lib/emoji.json but looks like I needed to be adding it in assets/emoji.json?

Could the one not being used be removed?

**Comment by ekmartin** [comment]
That's sloppy, sorry! I've removed `lib/emoji.json`. A pull request adding :slightly_smiling_face: would be awesome :)
