### ISSUE TITLE
Seems that the IRC-Part is going to sleep after a certain amount of time

### ISSUE THREAD

**Issue by heiglandreas** [ekmartin/slack-irc#16]
Could that be possible?

**Comment by ekmartin** [comment]
IRC-part = IRC bot? Doesn't seem to happen for me at least (three bots that have been alive since the release of 3.0). If you `export NODE_ENV=development` slack-irc will log debug info, so you'll see any IRC events.

**Comment by heiglandreas** [comment]
Thanks for the info! I'll check that and if I find anything usefull, I'll open an issue again!
