### ISSUE TITLE
Multiple identities in IRC

### ISSUE THREAD

**Issue by alexandernst** [ekmartin/slack-irc#168]
The current code spawns a bot and makes it join the IRC channel(s), then starts `/say`-ing everything that is being said in Slack.
Is there a way the code can be patched in such a way that instead of a single bot saying everything, multiple bots can join the channel(s), each one with it's own nick (mapped to a slack user), and make them say what each user in Slack says?

**Comment by ekmartin** [comment]
I've discussed this previously, but I think we concluded that it was too hard to get right and that it might have a few unwanted side effects. It might work okay for small channels, but would probably be a bit weird to scale for Slacks with thousands of users. If you're interested it should definitely be possible to implement in a fork though, but I'm gonna close this as I think it's quite different from slack-irc's existing functionality. 

Feel free to PM me on [Gitter](https://gitter.im/ekmartin/slack-irc) or similar if you want some tips in terms of how the current codebase could be changed to function like that though!
