### ISSUE TITLE
Add support for channel keys

### ISSUE THREAD

**Issue by flewid** [ekmartin/slack-irc#17]
Tried to get channel keys working, but was unable to do so, and doesn't look to be support for it yet, would be nice to add. 

I tried;

 "channelMapping": {
      "#channel-slack": "#irc-channel:pass"
    }

and

 "channelMapping": {
      "#channel-slack": "#irc-channel pass"
    }

with no luck

**Comment by ekmartin** [comment]
There's no support for that currently no. You can invite the bot to your channel though, as long as it's in the channel mapping.

```js
"channelMapping": {
   "#other-slack": "#secret-channel"
}
```

Then you can do `/invite botname #secret-channel`.

**Comment by flewid** [comment]
Hey, thanks for the reply on this; I had actually tried inviting the user, and authenticating it to nickserve too, and it gives me this (after restarting to ensure new config is used); 

error: Received error event from IRC prefix=card.freenode.net, server=card.freenode.net, command=err_badchannelkey, rawCommand=475, commandType=error, args=[mynickname, thechannel, Cannot join channel (+k) - bad key]

The current channel modes are; 

+gklnps

**Comment by ekmartin** [comment]
Yep, forgot that you still need a key even if you're invited. I'll make it possible to join channels with keys, should be fixed within a few hours :)

**Comment by ekmartin** [comment]
Fixed in [3.1.0](https://github.com/ekmartin/slack-irc/blob/master/CHANGELOG.md#310---2015-03-27). Just add the channel password after the channel name, i.e. `#channel password`.

**Comment by flewid** [comment]
Great thanks!

**Comment by flewid** [comment]
This is actually, still giving me the same error; 

error: Received error event from IRC prefix=kornbluth.freenode.net, server=kornbluth.freenode.net, command=err_badchannelkey, rawCommand=475, commandType=error, args=[nickname, #channelname, Cannot join channel (+k) - bad key]

i've double checked password, channel name. 

the mode is the same +gklnps

**Comment by ekmartin** [comment]
Are you sure you're using the latest version (3.1.0)? The channel mapping should look like this:
```json
"channelMapping": {
      "#slack": "#irc password"
}
```

Just tested with a channel with the exact same modes as yours (`+gklnps`), seems to work.

**Comment by flewid** [comment]
Yup, checked version in CHANGELOG

and my mapping is as such;

  "channelMapping": {

      "channel1": "#channel1 password",

      "channel2": "#channel2"

    }

is it because i'm doing it to a private group?

On Fri, Mar 27, 2015 at 5:07 PM, Martin Ek <notifications@github.com> wrote:

> Are you sure you're using the latest version (3.1.0)? The channel mapping
> should look like this:
>
> "channelMapping": {
>       "#slack": "#irc password"
> }
>
> Just tested with a channel with the exact same modes as yours (+gklnps),
> seems to work.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ekmartin/slack-irc/issues/17#issuecomment-87128093>.
>



-- 

      ∴ *Matthew Gibson*
*   CEO / Owner*
   Flewid Incorporated
   Cell: 612-206-7712
   flewid.ca | google+ <https://plus.google.com/+FlewidCa/posts> | facebook
<https://www.facebook.com/flewidinc>

**Comment by ekmartin** [comment]
Hm, should still work. Could you try adding a `debug: true` line [here](https://github.com/ekmartin/slack-irc/blob/master/lib/bot.js#L46) and see what it sends with the `JOIN` command (this should probably be a config option in the future)? I.e.:

```js
  this.ircClient = new irc.Client(this.server, this.nickname, {
    userName: this.nickname,
    realName: this.nickname,
    channels: this.channels,
    debug: true
  });
```
Then you should see something like `28 Mar 01:14:26 - SEND: JOIN #channel password`.

**Comment by flewid** [comment]
Sure, here it is; 

[Fri Mar 27 2015 19:38:26 GMT-0500 (CDT)] INFO Connecting...
27 Mar 19:38:26 - SEND: NICK myircnickname
27 Mar 19:38:26 - SEND: USER myircnickname 8 * myircnickname
27 Mar 19:38:27 - SEND: MODE myircnickname +x
27 Mar 19:38:27 - SEND: MSG nickserv :identify THISISMYPASSWORD
27 Mar 19:38:27 - Unhandled message: { prefix: 'verne.freenode.net',
  server: 'verne.freenode.net',
  command: 'rpl_luserunknown',
  rawCommand: '253',
  commandType: 'reply',
  args: [ 'myircnickname', '9', 'unknown connection(s)' ] }
27 Mar 19:38:27 - SEND: JOIN #channel1 password
27 Mar 19:38:27 - SEND: JOIN #channel2
27 Mar 19:38:27 - MODE: myircnickname sets mode: +i
27 Mar 19:38:27 - GOT NOTICE from "NickServ": "This nickname is registered. Please choose a different nickname, or identify via /msg NickServ identify <password>."
error: Received error event from IRC prefix=verne.freenode.net, server=verne.freenode.net, command=err_unknowncommand, rawCommand=421, commandType=error, args=[myircnickname, MSG, Unknown command]
error: Received error event from IRC prefix=verne.freenode.net, server=verne.freenode.net, command=err_badchannelkey, rawCommand=475, commandType=error, args=[myircnickname, #channel1, Cannot join channel (+k) - bad key]
27 Mar 19:38:32 - SEND: MODE #channel2
27 Mar 19:38:32 - Unhandled message: { prefix: 'services.',
  server: 'services.',
  command: '328',
  rawCommand: '328',
  commandType: 'normal',
  args: [ 'myircnickname', '#channel2', 'some message' ] }

**Comment by flewid** [comment]
here's my complete config file incase

[
  {
    "nickname": "myircnickname",
    "server": "irc.freenode.net",
    "token": "MYTOKEN",
    "autoSendCommands": [
        ["MODE", "myircnickname", "+x"],
        ["AUTH", "myircnickname", "THISISMYPASSWORD"]
    ],
    "channelMapping": {
      "irc-channel1": "#channel1 channelpassword",
      "irc-channel2": "#channel2"
    }
  }
]

**Comment by ekmartin** [comment]
It looks like it should, are you 100% sure that the key is correct? If you want to debug further you could try to execute the commands manually with telnet and see if it works then, i.e.:
```bash
$ telnet irc.freenode.net 6667
NICK myircnickname
USER myircnickname 8 * myircnickname
JOIN #channel1 password
```

**Comment by flewid** [comment]
Odd. We changed the key, changed it back to what it was previously, and
works. Thanks for all the help on this :)


On Fri, Mar 27, 2015 at 6:21 PM, Martin Ek <notifications@github.com> wrote:

> It looks like it should, are you 100% sure that the key is correct? If you
> want to debug further you could try to execute the commands manually with
> telnet and see if it works then, i.e.:
>
> $ telnet irc.freenode.net 6667
> NICK myircnickname
> USER myircnickname 8 * myircnickname
> JOIN #channel1 password
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ekmartin/slack-irc/issues/17#issuecomment-87137189>.
>



-- 

      ∴ *Matthew Gibson*
*   CEO / Owner*
   Flewid Incorporated
   Cell: 612-206-7712
   flewid.ca | google+ <https://plus.google.com/+FlewidCa/posts> | facebook
<https://www.facebook.com/flewidinc>
