### ISSUE TITLE
Bot using 443 port

### ISSUE THREAD

**Issue by duramato** [ekmartin/slack-irc#175]
The bot for some reason is using port 443, and that makes me unable to run a webserver.
Is it really needed?

**Comment by duramato** [comment]
I think this isn't an issue afterall, i was having issues of not beeing able to start lighttpd serving https becouse the 443 port was in use i then saw:
```
 lsof -i :443
COMMAND    PID     USER   FD   TYPE     DEVICE SIZE/OFF NODE NAME
node       505     root   12u  IPv4 2242324661      0t0  TCP 172.82.187.143:56319->ec2-52-90-64-91.compute-1.amazonaws.com:https (ESTABLISHED)
node       505     root   13u  IPv4 2242324662      0t0  TCP 172.82.187.143:52061->ec2-54-197-21-112.compute-1.amazonaws.com:https (ESTABLISHED)
```
Which gave me a missconception.

**Comment by ekmartin** [comment]
Hi, no worries. slack-irc shouldn't really bind any ports at all, so if it does - that's a bug.
