### ISSUE TITLE
Ready-made Docker container setup

### ISSUE THREAD

**Issue by caktux** [ekmartin/slack-irc#18]
https://github.com/caktux/slackbridge

Enjoy :)

**Comment by ekmartin** [comment]
Cool, thanks!

**Comment by garagatyi** [comment]
https://github.com/ekmartin/slack-irc/pull/25

**Comment by ekmartin** [comment]
I've added a link to it in the README, [here](https://github.com/ekmartin/slack-irc/pull/25#issuecomment-89853502).
