### ISSUE TITLE
run as a service

### ISSUE THREAD

**Issue by ssbarnea** [ekmartin/slack-irc#188]
We need a solution for running it as a service, or to something that is closer to a service.

**Comment by ekmartin** [comment]
There's a variety of tools you can use to keep it alive:
* [supervisord](http://supervisord.org/)
* [pm2](https://github.com/Unitech/pm2) (Node.js only)
* [forever](https://github.com/foreverjs/forever)

If you're running a Linux system that supports it you can also just use systemd, which is probably the simplest option.

**Comment by ekmartin** [comment]
Or did I misunderstand what you meant with running it as a service?
