### ISSUE TITLE
Slackbot custom commands don't display on IRC

### ISSUE THREAD

**Issue by Stoner19** [ekmartin/slack-irc#206]
I've created some custom responses for Slackbot (the native bot included with all Slack teams) and for some reason it won't display any of the responses in IRC. Although it does show the `command send by <user>` when the custom response is triggered from Slack. 

I have included the proper lines in my JSON config but it still will not display on IRC.
```
    "commandCharacters": ["!", "."],
    "muteSlackbot": false
```

**Comment by ekmartin** [comment]
This is because of #50.

**Comment by Stoner19** [comment]
Maybe an easier solution might be to include optional commands within the slack-irc bot that are written to IRC? So long as the bridge is connected the returned commands will display on Slack. Unless this is already a feature and I'm totally missing it within the source.
