### ISSUE TITLE
Not able to use after updating to latest version

### ISSUE THREAD

**Issue by duramato** [ekmartin/slack-irc#208]
I just updated to the latest npm version and i'm starting to get
`error: Maximum IRC retry count reached, exiting.` 
something which i hadn't experienced before upgrading

Connecting to freenode

**Comment by ekmartin** [comment]
Can you set `debug` to true in your `ircOptions` object? That'll give you some more information.
I.e.:

```json
    "ircOptions": {
      "debug": true
     }
```

in the config.
