### ISSUE TITLE
README now clear on where things need to be installed

### ISSUE THREAD

**Issue by douglasawh** [ekmartin/slack-irc#209]
I'm definitely a slack n00b. I have slightly more experience in IRC, but I know basically nothing about managing one.

A volunteer org I essentially run has a channel on freenode and a slack. Running the npm command sounds easy enough, but I don't have access to slack or freenode servers, so...where do I run this? Do I just run it on a separate server and all the traffic goes through the third server?

I'm happy to give exact names of the freenode channel and such if that is helpful, but that feels spammy.

**Comment by ekmartin** [comment]
Yes, exactly. You run the bot on a server you own, such as one from [DigitalOcean](https://digitalocean.com) etc. There are a few services that make hosting Node.js stuff easier, but they often pause your service from time to time which makes it less than perfect for bots. 

Let me know if you have any other questions about how to keep it running etc.
