### ISSUE TITLE
Feature Request: Allow bot to simulate direct messages

### ISSUE THREAD

**Issue by ahungry** [ekmartin/slack-irc#216]
I find this relay almost perfect for doing all my slack conversing over IRC using my preferred IRC client(s), however, it seems there is no support for direct messages (if I receive a message over slack).

I would like to see something (I may hack at it and create a PR) to accomplish:

- If I receive a slack message, a one on one IRC channel will be opened
- If I use the standard IRC command, /msg some-nick, a one on one IRC channel will be opened
- If I send a message to this one on one channel, it will be received by the slack user

I think to do this may require simulating each slack messenger as an IRC user, instead of using the general slack-relay (s-rel) user - assuming this repo uses the wss (RTM from slack), those direct messages should be coming through very similarly to the channel messages.

The use case for this is for when the slack (server side) has IRC support turned off due to security reasons, but still allows the API to be opened up.

Is there anything similar or that has ever been considered previously?

**Comment by ekmartin** [comment]
I've generally avoided adding stuff like direct message support in the past to keep the focus on slack-irc as a bridge, and not a personal client. There's a [slack-irc-client](https://github.com/aeirola/slack-irc-client) project that does basically what you're describing, but in the other direction (using Slack as an IRC client).

If you really want to do this I think it'd be best to start from scratch (or fork this project). There's an argument to be held that this exposes the exact same security risk as enabling the IRC bridge itself though, but I'll leave that up to you.

**Comment by ahungry** [comment]
Thanks!
