### ISSUE TITLE
Dockerize slack-irc

### ISSUE THREAD

**Issue by mrhillsman** [ekmartin/slack-irc#219]
Would be great to be able to utilize slack-irc via a docker container. I recently decided to grab cloud virtual machine to try out a number of applications wanting to avoid the difficulties of install/uninstall of said applications outside of a container. I will create a pull request of what I used to successfully dockerize slack-irc.

**Comment by ekmartin** [comment]
Hi @mrhillsman! There's a [docker image](https://github.com/caktux/slackbridge/) linked to in the README. It looks like it has a couple of open PRs that could need merging though, so if your image has substantial improvements I'd be happy to link to that instead of the old one in the README.

**Comment by mrhillsman** [comment]
Hey @ekmartin, thanks for update. Yes, I was just finishing up and submitted PR, please let me know if any changes required and thank you for an awesome tool!
