### ISSUE TITLE
New (updated) Docker container for slack-irc

### ISSUE THREAD

**Issue by dkorunic** [ekmartin/slack-irc#223]
Hi, I've took a peek at existing slackbridge Docker container [https://github.com/caktux/slackbridge](https://github.com/caktux/slackbridge) and found out it's ancient to say at least (Ubuntu Willy, NodeJS 5.x, runs slack-irc as root, doesn't use Compose etc.). I've forked and updated the project accordingly here:

[https://github.com/dkorunic/slackbridge](https://github.com/dkorunic/slackbridge)

I would appreciate if you could link to that project too. Thanks!

**Comment by bovine** [comment]
@dkorunic Your fork appears to be deleted now. Maybe close this issue?

**Comment by dkorunic** [comment]
Absolutely.
