### ISSUE TITLE
Missing Configuration Field Server

### ISSUE THREAD

**Issue by allencoded** [ekmartin/slack-irc#23]
I made a config and then go to run the config:
```slack-irc --config config.js```

Get error thrown:
/usr/local/lib/node_modules/slack-irc/lib/bot.js:17
      throw new errors.ConfigurationError('Missing configuration field ' + fie
            ^
ConfigurationError: Missing configuration field server

Oddly it says there is a configuration field server in fact here is my config as it stands:

```json
[
  {
    "nickname": "ircbot",
    "server": "morgan.freenode.net",
    "token": "<HIDDEN>", // Your bot user's token
    "autoSendCommands": [ // Commands that will be sent on connect
        ["PRIVMSG", "NickServ", "IDENTIFY password"],
        ["MODE", "test", "+x"],
        ["AUTH", "test", "password"]
    ],
    "channelMapping": { // Maps each Slack-channel to an IRC-channel, used to direct messages to the correct place
      "#slack": "#irc-test", // Add channel keys after the channel name
    }
  }
]
```

Any advice?

**Comment by ekmartin** [comment]
Hi! The configuration file needs to be saved as a `.json`-file, not `.js`. You also need to remove the comments for it to be valid JSON :)

**Comment by ekmartin** [comment]
That is, you could save it as a `.js`-file if you really wanted to, but then you'd need to `module.exports` the config object/array.
