### ISSUE TITLE
command=err_cannotsendtochan, rawCommand=404

### ISSUE THREAD

**Issue by allencoded** [ekmartin/slack-irc#24]
I was succesfully able to connect to a freenode server. When I try to send a chat from slack though I get:
`Received error event from IRC prefix=asimov.freenode.net, server=asimov.freenode.net, command=err_cannotsendtochan, rawCommand=404, commandType=error, args=[getdevs, #csharp, Cannot send to channel]`

How does one connect to a freenode chat server and have the ability to send and recieve messages?

**Comment by ekmartin** [comment]
Do you have `#csharp` in your channel mapping? Else the bot won't join the channel.
I.e., something like: 
```json
"channelMapping": {
  "#slackChannel": "#csharp"
}
```

Also, does `#csharp` have `+m` enabled? If so the bot needs to be voiced to be able to talk.

**Comment by allencoded** [comment]
Yeah I am using the above mapping. In fact it seems to add the user to the IRC chat room just doesn't allow me to type anything and what others type doesn't come back across the wire to my slack channel. Everytime I type something I get the above error. 

`{
    "nickname": "getdevs",
    "server": "chat.freenode.net",
    "token": "HIDDEN",
    "autoSendCommands": [
      ["PRIVMSG", "NickServ", "IDENTIFY getdevs password"],
      ["MODE", "getdevs", "+x"],
      ["AUTH", "getdevs", "password"]
    ],
    "channelMapping": {
      "#csharp": "#csharp" 
    }`

The above has all the passwords and tokens hidden of course, but I have played around with the autoSendCommands. I feel like I am missing a command or not using one of them correctly. 

It is only for freenode that is problematic. I was able to connect esper quite fine and it worked successfully there. But the channel I am needing as you can see above is #csharp which resides in freenode.

**Comment by ekmartin** [comment]
Maybe because the channel name is `##csharp` with two squares? The joining probably works since it gets redirected, but it'll still try to send messages to `#csharp` and **not** `##csharp`, which is the actual channel name.

**Comment by allencoded** [comment]
That was exactly it. Using ##csharp did the trick thanks.

**Comment by ekmartin** [comment]
No problem, feel free to ask if more problems show up :)
