### ISSUE TITLE
Only token accepted when Slack now uses a full URL

### ISSUE THREAD

**Issue by k3ilbasa** [ekmartin/slack-irc#28]
There is only a token accepted in the config.json file, but when I create a slackbot, they give me a personal URL to use instead.  Am I doing something incorrectly here?

**Comment by ekmartin** [comment]
Hi! You should be creating a Slack bot user (not adding a Slackbot integration):
![image](https://cloud.githubusercontent.com/assets/3536982/7394626/03286140-ee95-11e4-989e-9d4930aed37d.png)

It's available from the same place you found the Slackbot integration. It's a bit confusing :confused: 
Then you should get an API token like this:
![image](https://cloud.githubusercontent.com/assets/3536982/7394622/fa12fbb0-ee94-11e4-9024-9870a893c09b.png)

**Comment by k3ilbasa** [comment]
Aha! I was using the SlackBot, not a regular bot.  Thanks for the explanation!

**Comment by ekmartin** [comment]
No problem :)

**Comment by k3ilbasa** [comment]
So, you have a docker linked in the bottom of the readme on your page, can you explain what that is used for?  Sorry for such a simple question.

**Comment by ekmartin** [comment]
It's just a Dockerfile that sets up an Ubuntu container with node.js and slack-irc - no need for it if you don't want to run slack-irc inside a Docker container :)

**Comment by k3ilbasa** [comment]
So, I would use that to keep my slack-irc runnig in the background of my server?

**Comment by ekmartin** [comment]
No, you don't need Docker for that. You can use anything that's made for keeping a process alive as a daemon. If you're cloning the repository you can run `index.js` with node through something like [nodemon](https://github.com/remy/nodemon) or [forever](https://github.com/foreverjs/forever).

I'm running slack-irc on an Ubuntu server, so I have an init.d service that runs `index.js` with forever. It looks like this: https://gist.github.com/ekmartin/8423b95bb15196e33196 - however it'll work nicely if you just install forever and run `forever start index.js --config config.json` too (which will start it in the background).

**Comment by k3ilbasa** [comment]
Thanks for that information, that's exactly what I want to do.
