### ISSUE TITLE
Join/Part Option Unavailable 

### ISSUE THREAD

**Issue by robertkety** [ekmartin/slack-irc#32]
The option to toggle join/part messages would be nice.

**Comment by robertkety** [comment]
Our team is using this to move away from our IRC clients and into Slack.  The messaging component works great, but users that enter the IRC channel see no one but the bot.  Also, Slack users are unaware that anyone has joined/parted the IRC channel. An option to enable join/part for IRC/Slack users would be greatly appreciated.

**Comment by robertkety** [comment]
I'm not all that familiar with node, but could we add the following to lib\bot.js in Bot.prototype.attachListeners?

this.ircClient.on('join', this.sendToSlack.bind(this));
this.ircClient.on('part', this.sendToSlack.bind(this));

**Comment by ekmartin** [comment]
No, the `join` and `part` event callbacks don't use the same arguments as the `message` event, so you'd need to change it up a bit first. See https://node-irc.readthedocs.org/en/latest/API.html#'join' for more information. 

It wouldn't require that much changes though, so it's certainly doable. However, is it really that useful? Users that enter the IRC channel will still see no one but the bot (see #34). The only real usecase I could see would be if you're talking with someone, and that someone disconnects/parts, but is that really worth the join/part spam an IRC channel often comes with?

It would be possible to show join/parts from the Slack channels too, but aren't these quite seldom anyway? I mean, it would only show the first time a user joined a channel, and not when they disconnect/connect to Slack later on. For this you'd have to listen for [precense_change](https://node-irc.readthedocs.org/en/latest/API.html#'join')-events, but I think that'd be way too much spam if you have a decently sized Slack team (it would also fire for everyone in the Slack team, not just the people in the channel).

**Comment by robertkety** [comment]
I found that huge switch/case in nose-irc that provides the proper arguments. I have a successful implementation in my fork if you're interested. Perhaps my team has a unique need for the feature, but we find it useful for monitoring our rarely-used public irc channel. We're using slack-irc to move away from irc while still offering the option to users that prefer it.

----- Reply message -----

**Comment by robertkety** [comment]
https://github.com/robertkety/slack-irc/tree/Join/Part

**Comment by ekmartin** [comment]
This has been fixed in master. Will publish a new version including it as soon as a few other changes have landed.
