### ISSUE TITLE
Presence awareness

### ISSUE THREAD

**Issue by gtirloni** [ekmartin/slack-irc#34]
From a cursory look through the Slack API this does not seem possible, but I will through it here to get more feedback.

One drawback of using an IRC bridge is that presence awareness is impacted. People on IRC do not know who's is online behind the bot and vice-versa.

Ideally, it should be possible to create "fake" users in Slack to represent people on IRC. Doing the same on IRC would be tricky to say the least.

That being said, perhaps relaying join/part/quit messages would be interesting, but I'm not sure how annoying that would be (or useful, because people would have to parse the channel instead of checking a user list).

**Comment by ekmartin** [comment]
It'd certainly be useful if it was possible, but as you're saying it's quite hard to achieve. I don't think there's any decent way to do it all through the Slack API. The other way (Slack -> IRC) you could of course spawn an individual IRC bot for each user in a Slack room, but I don't think that's really a viable solution in the long run (see #19 for a somewhat related discussion).

There's an open issue about join/part-messages here: #32, but I don't think it'd help much with the issue you're raising here.

**Comment by ekmartin** [comment]
Closing this. A bit related to https://github.com/ekmartin/slack-irc/issues/42#issuecomment-128113531 with the user lists, so check that for a more thorough explanation.

As for join/part messages, see #32.
