### ISSUE TITLE
Improve Docker workflow

### ISSUE THREAD

**Issue by mrsmn** [ekmartin/slack-irc#36]
Hi there,

I have created an Alpine Linux based Docker image for slack-irc. Compared to @caktux image, this takes up 27MB of disk space instead of 400MB and builds in about 20 seconds instead of 3 minutes 50 seconds.

I you don't want to build the image yourself, [you can even pull it from the Docker Hub](https://registry.hub.docker.com/u/1024/slackirc/). This takes about 10 seconds.

Cheers.

**Comment by ekmartin** [comment]
Cool, but not sure if there's any point in having two separate Dockerfiles linked in the README. Just out of curiousity, what node version does `apk add --update nodejs` result in? Also, do you use supervisor or something similar together with `docker run` to ensure that it's kept running?

**Comment by mrsmn** [comment]
Hi there,

the NodeJS version running in that container is ```0.12.2```. No need for supervisor: as long as the container runs, slack-irc runs.

Cheers.
