### ISSUE TITLE
/me's aren't bridged either way

### ISSUE THREAD

**Issue by callumacrae** [ekmartin/slack-irc#37]
/me is built in to both slack and irc and does the same thing on both platforms. slack-irc ignores them, though :disappointed:

**Comment by ekmartin** [comment]
https://github.com/ekmartin/slack-irc/pull/15 - @heiglandreas started working on this, but don't think he's had time to finish it yet.

**Comment by heiglandreas** [comment]
Too much other things around :(

Have a look at https://github.com/ekmartin/slack-irc/pull/15

**Comment by callumacrae** [comment]
Awesome! Thanks for slack-irc, we literally couldn't use Slack without it.

**Comment by ekmartin** [comment]
No problem, thank you for the kind feedback. @heiglandreas are you planning to finish it when you get time? If not I'll take a look at it :)

I'll reopen this issue until it's fixed at least, should definitely be supported.

**Comment by heiglandreas** [comment]
Oh I intend to. It's just a matter of time :frowning: I hope to get to it during the next weekend...

**Comment by ekmartin** [comment]
Cool! No rush :smile:

**Comment by ekmartin** [comment]
This has been added in [3.6.0](https://github.com/ekmartin/slack-irc/blob/master/CHANGELOG.md#360---2015-09-14). IRC actions will be posted to Slack formatted with italics, Slack actions will be prefixed with `Action: `.
