### ISSUE TITLE
IRC Notifications not sent to Slack

### ISSUE THREAD

**Issue by jdogcisco** [ekmartin/slack-irc#39]
This is a very slick tool.  Good job.  It's helping to bridge the two systems for us.  Is there anyway to get IRC notifications sent to Slack as well?

An example:
15:44 -ovplus_:#ptac- [#29139 New] "How Can We Push This To Slack?" from ABC Company (https://ABCCompany.com/90000040000ngSsoAAE)
15:44 < jdog> Level_1: just a test ^ I will delete

The first entry does not get pushed, the second does.

**Comment by robertkety** [comment]
Are you asking about notices? There is large switch/case at https://github.com/martynsmith/node-irc/blob/master/lib/irc.js that details the different IRC listeners available.  I don't think the slack-irc bot handles notices though (https://github.com/robertkety/slack-irc/blob/Join/Part/lib/bot.js)

**Comment by jdogcisco** [comment]
Yes, notices. Bummer if slack-irc can't handle these.

**Comment by robertkety** [comment]
Should be easy enough to implement:

<code>this.ircClient.on('notice', this.sendToSlack.bind(this));</code>

Add that line of code to https://github.com/robertkety/slack-irc/blob/Join/Part/lib/bot.js around line 86 before deploying the service.

**Comment by jdogcisco** [comment]
That's great!  Thanks so much!  It's passing notices now.

**Comment by ekmartin** [comment]
This should definitely be supported in slack-irc. If one of you'd want to send a pull request that'd be cool!

**Comment by robertkety** [comment]
Pull requested.  Also included join/part/quit and welcome message features from my fork.

**Comment by mcbridem** [comment]
It looks like <https://github.com/ekmartin/slack-irc/pull/41> is the relevant pull request.

**Comment by ekmartin** [comment]
This has been added in [3.6.0](https://github.com/ekmartin/slack-irc/blob/master/CHANGELOG.md#360---2015-09-14). Notices will be posted to Slack, prefixed with `Notice: `.
