### ISSUE TITLE
User Lists and Avatars

### ISSUE THREAD

**Issue by Reziun** [ekmartin/slack-irc#42]
Hello! 

I've just installed this and it's working great! I do have a couple questions I'd like to ask though...
1) Is there a way to get users on slack from irc and irc from slack?
2) Is there a way to customize the avatars, or a way to edit them?

Thanks for this fantastic plugin!
-Rez

**Comment by ekmartin** [comment]
Hi, and thank you for the feedback :smile: 

> 1) Is there a way to get users on slack from irc and irc from slack?

No, there's no way to do this at the moment. It's been suggested that the bot should display join/part messages on Slack whenever people join or leave the connected IRC channels. Was this what you're thinking of, or do you want a complete list of all the people in the respective channels? That could be possible too, but it would've to be implemented as some sort of command, i.e. /list #channel to the bot, and I'm not sure if it's worth the extra complexity.

> 2) Is there a way to customize the avatars, or a way to edit them?

At the moment you'd have to fork the repository and modify this property: https://github.com/ekmartin/slack-irc/blob/master/lib/bot.js#L169
I've thought about adding a configuration option for it, something like:
```json
"iconUrl": "http://some-url.com/${username}"
```
and replace `${username}` with the actual username, but I haven't gotten around to it yet. I'm also a bit wary of adding too many configuration options, as what slack-irc really isn't that complicated (and thus shouldn't require that many options). However, I've noticed other people wanting to modify it too, so it might be useful.

**Comment by Reziun** [comment]
1) I'm looking more for the latter option being able to do /list #channel from Slack to see who's on IRC and then also possibly finding a to see who's online in slack for users on irc through commands similar to the this:
http://stackoverflow.com/questions/26220446/how-do-i-get-a-users-online-status-via-the-slack-api

2) That would make sense, but essentially it would require a lot of avatars to allow for a unique avatar for each IRC user. Thanks for that info! (This part is solved)

**Comment by ekmartin** [comment]
Closing this for now. Your first issue could be doable, but it'd probably require quite a lot of added complexity and I'm trying to keep slack-irc as compact as possible for the moment.

Feel free to open a separate issue if you feel there should be a config variable for your second issue (the icon avatars).
