### ISSUE TITLE
Forward commands from slack to irc w/o prefacing with nick

### ISSUE THREAD

**Issue by jdogcisco** [ekmartin/slack-irc#43]
Enjoying slack-irc very much. Thank you!  I was wondering if it is possible to forward commands from slack to IRC without the bot prepending the nick that issued the command.  Our commands are started with an explanation point "!".  For example:

07:29 < jdog> !netintime
07:29 < Karsten> Fremont: 07:29 Varberg/Malmö: 16:29 Kelowna: 07:29 Seoul: 23:29 Melbourne: 00:29 Hong Kong: 22:29 Boston: 10:29

If we try from slack, the "!" isn't the first character on the line, our nick is.  For example:
07:30 < McBot> <jdog> !netintime
No results. The line above should have the nick listed between mcbot's nick and the command. When I save this comment, it disappeared - making it look how I envision the command should be sent.

Thanks again!

**Comment by dstinebaugh** [comment]
I'm actually looking for a solution to this as well for a !google script, I was looking at rebuilding the script to ignore anything between <> marks, but also think an option inside of slack-irc to disable, or mabye add the nick as a suffix to the text, would be handy as well

**Comment by ekmartin** [comment]
Sorry for the late answer. It could be possible to have an option with an array (or similar) of characters that'd make the bot output the message directly instead of with a username first. I.e., something like:
```json
"commandCharacters": ["!", "."]
```

This could work as long as it's off by default (so it isn't a possible security risk).

**Comment by andebor** [comment]
I agree. That sounds like the best solution. Could probably just add another parser to `sendToIRC`.

**Comment by ekmartin** [comment]
Fixed in #45, would this fit your use cases @jdogcisco and @dstinebaugh?

If you for example use `"commandCharacters": ["!"]` a message like `!hi` will be posted directly to IRC as `!hi`. 

I'm a bit unsure if it's bad that it completely hides the Slack author, however I'm not sure if there's a clean solution for it. I think appending the nick as a suffix makes it a bit pointless, as it'll break the behavior of a lot of IRC bots. One option could be to post commands to IRC like this:
```
SlackIRCBot: Command posted by SlackUsername:
SlackIRCBot: !command
```
or
```
SlackIRCBot: <SlackUsername>
SlackIRCBot: !command
```

But I'm not sure if it's a bit too verbose. Also, since the default option is just an empty array, it's not like it's a security risk or anything.

**Comment by dstinebaugh** [comment]
This would indeed fix my issue!

**Comment by jdogcisco** [comment]
Either option is acceptable.  Thanks much!  Is this ready now?  How do I update?

**Comment by ekmartin** [comment]
I haven't merged in the pull request yet as it currently only posts the command without saying who posted it to Slack. Think I'll go for the `Command sent from Slack by SlackUsername:` option.

**Comment by ekmartin** [comment]
It's published to npm now (version 3.5.0). @jdogcisco, have you installed slack-irc as a global npm dependency? If so you can just run `npm update -g slack-irc`.

**Comment by jdogcisco** [comment]
@ekmartin Thanks.  It seems to have updated.  However, I'm not getting expected results...

![fromslack](https://cloud.githubusercontent.com/assets/8601936/8291130/5a557d92-18dc-11e5-9f45-5dab8e2b50a4.png)
![fromirc](https://cloud.githubusercontent.com/assets/8601936/8291132/5d01c316-18dc-11e5-9945-f58fa1227ca1.png)

The disconnect and reconnect on the IRC channel is when I upgraded.  I cross checked the files individually and it looked like they have all the updates you made.

**Comment by andebor** [comment]
@jdogcisco Have you remembered to add the command character to your config file?

**Comment by jdogcisco** [comment]
@andebor No!  I didn't realize that was required.  It's working now.  Thanks much!
@ekmartin I'm good. Thanks again for this!

**Comment by ekmartin** [comment]
:+1: @andebor

**Comment by dstinebaugh** [comment]
Just wanted to chime in that indeed, this works great and solved my issue as well! Thanks again!
