### ISSUE TITLE
Map IRC usernames to slack usernames and vice versa (with notification support)

### ISSUE THREAD

**Issue by alias1** [ekmartin/slack-irc#46]
Being able to "@username" (or even just "username") in IRC and have it notify in slack would be great.

**Comment by andebor** [comment]
This has been working pretty much since the first version, if I'm understanding your question correctly. The only thing thats not possible as of now, is the ability to tab-complete usernames from irc in slack and vice versa. 

Have you tried what you're asking? It's working both ways here.

**Comment by alias1** [comment]
Including the mapping different names between irc/slack? If so, then my bad.

**Comment by andebor** [comment]
What are you asking, @alias1? Are you connected to the same channel with both an irc client and a slack client? and with different usernames? 
This would be much more efficient if you would just test the functionality yourself rather than us trying to figure out what you're trying to accomplish.

**Comment by alias1** [comment]
Created the issue because there is no way, as I can see documented, to map mentions of UsernameA in IRC to notify UsernameB in slack.

But don't worry about it.

**Comment by ekmartin** [comment]
That's a completely valid point. Are you thinking of some kind of functionality where you create a username mapping in the configuration file (between Slack and IRC usernames)? I understand how that could be useful, but I think it'd require too much configuration for most users.

**Comment by alias1** [comment]
*nods* that's how I saw it done in one of the other slack-irc bridges.




Yeah, potentially would be. Food for thought in any case.



—

**Comment by ulion** [comment]
Which would be very useful to us, kodi team, we had irc channel for team users, now slack channel, but they may use different username, so support that would be sweet.
