### ISSUE TITLE
After running for a while, Slack messages are no longer sent to IRC

### ISSUE THREAD

**Issue by Vilkku** [ekmartin/slack-irc#49]
Pretty much what the title says. I am unsure of exact times slack-irc needs to be running, but I would estimate about a week (could note for the record that it happened again just now). IRC messages continue to be sent to Slack without problems, which makes it a bit difficult to spot.

I'm running 3.5.2.

**Comment by Vilkku** [comment]
After further research it looks like this might be a duplicate of https://github.com/ekmartin/slack-irc/issues/30, apologies. Close if that is the case.

**Comment by ekmartin** [comment]
It's a bug in node-slack-client, but yes, duplicate of #30.
