### ISSUE TITLE
AUTH ?

### ISSUE THREAD

**Issue by Niler851** [ekmartin/slack-irc#52]
["AUTH", "test", "password"]

that isent even a irc command ?

Also can you add some documentation on what thoes messages are for ?

[Sat Sep 05 2015 12:00:54 GMT-0400 (EDT)] INFO Connecting...
error: Received error event from IRC prefix=weber.freenode.net, server=weber.freenode.net, command=err_unknowncommand, rawCommand=421, commandType=error, args=[irc-bot, AUTH, Unknown command]

**Comment by ekmartin** [comment]
For some networks AUTH is a command, e.g. QuakeNet: https://www.quakenet.org/help/q-commands/auth

To auth through Freenode you need to message NickServ, which can be done through the other command listed in the README: `["PRIVMSG", "NickServ", "IDENTIFY password"]`. This would be the eqvuivalent of writing `/msg NickServ IDENTIFY password` in your IRC client.

For a full list of regular IRC commands, see: https://en.wikipedia.org/wiki/List_of_Internet_Relay_Chat_commands

I'm not sure what you mean with
> Also can you add some documentation on what thoes messages are for ?

Are you talking about the error message from Freenode or the `["AUTH", "test", "password"]` command?
