### ISSUE TITLE
Some serious spaming 

### ISSUE THREAD

**Issue by Niler851** [ekmartin/slack-irc#53]
note1989_BOT 8:24 PM [felansu] hello people, any grails programmer here?
[note1989_] [felansu] hello people, any grails programmer here?
[note1989_] [note1989_] [felansu] hello people, any grails programmer here?
[note1989_] [note1989_] [note1989_] [felansu] hello people, any grails programmer here?
[note1989_] [note1989_] [note1989_] [note1989_] [felansu] hello people, any grails programmer here?
[note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [felansu] hello people, any grails programmer here?
[note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [felansu] hello people, any grails programmer here?
[note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [felansu] hello people, any grails programmer here?
[note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [felansu] hello people, any grails programmer here?
[note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [felansu] hello people, any grails programmer here?
[note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [felansu] hello people, any grails programmer here?
[note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [felansu] hello people, any grails programmer here?
[note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [felansu] hello people, any grails programmer here?
[note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [felansu] hello people, any grails programmer here?
[note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [felansu] hello people, any grails programmer here?
[note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [felansu] hello people, any grails programmer here?
[note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [felansu] hello people, any grails programmer here?
[note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [felansu] hello people, any grails programmer here?
[note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [felansu] hello people, any grails programmer here?
[note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [felansu] hello people, any grails programmer here?
[note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [felansu] hello people, any grails programmer here?
[note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [felansu] hello people, any grails programmer here?
[note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [felansu] hello people, any grails programmer here?
[note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [felansu] hello people, any grails programmer here?
[note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [felansu] hello people, any grails programmer here?
[note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [felansu] hello people, any grails programmer here?
[note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [felansu] hello people, any grails programmer here?
[note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [felansu] hello people, any grails programmer here?
[note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [felansu] hello people, any grails programmer here?
skeasorBOT 8:52 PM never knew there was a angularjs on irc...nice
PinglessBOT 8:54 PM I've got a directive with a custom controller, and I need to access the directive's elements from the controller. Is there a way to do that, or should I rethink my approach?
felansuBOT 8:56 PM Pingless: maybe this can help you https://github.com/felansu/QRBWEB/blob/master/src/client/main/app/components/author/create/author.create.controller.js
Oh Pingless, sorry. I read wrong...
i'm thinking in factories...
PinglessBOT 9:02 PM felansu: oh right, I was a little confused...
note1989_BOT 9:02 PM [Pingless] felansu: oh right, I was a little confused...
[note1989_] [Pingless] felansu: oh right, I was a little confused...
[note1989_] [note1989_] [Pingless] felansu: oh right, I was a little confused...
[note1989_] [note1989_] [note1989_] [Pingless] felansu: oh right, I was a little confused...
[note1989_] [note1989_] [note1989_] [note1989_] [Pingless] felansu: oh right, I was a little confused...
[note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [Pingless] felansu: oh right, I was a little confused...
[note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [Pingless] felansu: oh right, I was a little confused...
[note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [Pingless] felansu: oh right, I was a little confused...
[note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [Pingless] felansu: oh right, I was a little confused...
[note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [Pingless] felansu: oh right, I was a little confused...
[note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [Pingless] felansu: oh right, I was a little confused...
[note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [Pingless] felansu: oh right, I was a little confused...
PinglessBOT 9:02 PM can someone boot that bot?
note1989_BOT 9:02 PM [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [Pingless] felansu: oh right, I was a little confused...
[Pingless] can someone boot that bot?
[note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [Pingless] felansu: oh right, I was a little confused...
[note1989_] [Pingless] can someone boot that bot?
[note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [Pingless] felansu: oh right, I was a little confused...
[note1989_] [note1989_] [Pingless] can someone boot that bot?
[note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [Pingless] felansu: oh right, I was a little confused...
[note1989_] [note1989_] [note1989_] [Pingless] can someone boot that bot?
[note1989_] [note1989_] [note1989_] [note1989_] [Pingless] can someone boot that bot?
[note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [Pingless] felansu: oh right, I was a little confused...
[note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [Pingless] can someone boot that bot?
[note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [Pingless] felansu: oh right, I was a little confused...
[note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [Pingless] can someone boot that bot?
[note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [Pingless] felansu: oh right, I was a little confused...
[note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [Pingless] can someone boot that bot?
[note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [note1989_] [Pingless] felansu: oh right, I was a little confused...

**Comment by Niler851** [comment]
the stange thing is that my bot is called irc-bot. note1989 is my other irc account. i registered irc-bot and grouped it to my other acount with NickServ

**Comment by ekmartin** [comment]
Not completely sure what I'm looking at here, but maybe you're running multiple bots (or someone else is running a bot in that channel).

**Comment by Niler851** [comment]
havent really look that much into it. is there any logfiles i can look at ?

**Comment by ekmartin** [comment]
If you do `export NODE_ENV=development` before running the bot it'll output more log info to stdout - no log files are created.

**Comment by ekmartin** [comment]
Closing this as I don't think slack-irc was the result of the problem, feel free to reopen if you can reproduce.
