### ISSUE TITLE
Nick list from slack?

### ISSUE THREAD

**Issue by chx** [ekmartin/slack-irc#61]
Is it possible to query the slack channel about who is there?

**Comment by ekmartin** [comment]
No, that's not possible at the moment. As far as I can see this isn't supported by [node-slack-client](https://github.com/slackhq/node-slack-client) either, but if you want to get it working in a fork you could use [this.slack's](https://github.com/ekmartin/slack-irc/blob/master/lib/bot.js#L25) private `_apiCall` method (from here: https://github.com/slackhq/node-slack-client/blob/5cc18662ca09c299ff3a93a109803d728ab77616/src/client.coffee#L539) in the following way:

```js
var channelId = this.slack.getChannelByName('#channel-name');
this.slack._apiCall('channels.info', { channel: channelId }, callback);
```

The `channel.info` API endpoint is documented here: https://api.slack.com/methods/channels.info.

I'm gonna close this, as I don't think this is something that is needed in slack-irc's core functionality.
