### ISSUE TITLE
Issue with outgoing webhook

### ISSUE THREAD

**Issue by notdoug** [ekmartin/slack-irc#7]
First of all, thanks for this, @ekmartin - this is exactly what I was looking for.

I got everything set up using the readme, but unfortunately I'm running into an issue with the outgoing webhook. I can get messages into Slack from IRC, but outgoing messages aren't working at all.

* I added the URL to my server to the webhook settings (using port 3000 based on what I was able to find poking around the code) and it doesn't seem to be responding.

* I tried to throw some POSTs at it using [Postman](https://chrome.google.com/webstore/detail/postman-rest-client/fdmmgilgnpjigdojojpjoooidkmcomcm?hl=en), too, but I'm getting a 404. Additionally, Slack sent me an email saying the outgoing webhook wasn't working properly. 

I did my best to figure this out by reading and trying different things, but I'm not sure what else to do.

Is there an additional setup step I am missing? I'll gladly make up a PR with the additional steps to help other folks, as well.

Thanks for any input!

**Comment by ekmartin** [comment]
Hi!
At the moment the outgoing integration needs to POST to [/send](https://github.com/ekmartin/slack-irc/blob/c7072bc0c2289eab8178d870fdcc6392fe002988/lib/server.js#L17) of the URL slack-irc is running at, i.e. `http://yourslackircurl.com/send`. The default port is 3000, but it can be set by exposing the environment variable `PORT`. 

I thought I had clarified this in the README, but apparently not. Might be that the URL should be changed to just `/`, as that would probably be more intuitive.

**Comment by notdoug** [comment]
That was exactly it - after adding ```/send``` it works perfectly. Thanks for the help!

I tried to make a PR to update the readme, but I guess I don't have permission, sorry. 

Thanks again for the help!

**Comment by ekmartin** [comment]
No problem :). To make pull requests you need to fork the repository, but I think I'm going to change the URL to just be at `/`.

**Comment by ekmartin** [comment]
Changed from `/send` to `/` in https://github.com/ekmartin/slack-irc/commit/8003e0b8841b367ed125cd8dd35ad6f7af50da19, released version 2.0.0 on npm as it's a backwards incompatible change.
