### ISSUE TITLE
Missing "babel-polyfill" dependency?

### ISSUE THREAD

**Issue by nevik** [ekmartin/slack-irc#71]
Hey again, after having #70 fixed in v3.7.1, I've tried running slack-irc again. This time, I got a different error :/

```
$ ~/node_modules/.bin/slack-irc --config slackrelay_config.json
module.js:338
    throw err;
          ^
Error: Cannot find module 'babel-polyfill'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (~/node_modules/slack-irc/dist/index.js:8:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
```

Since this seemed to me like a missing dependency-entry, I manually installed `babel-polyfill` and tried again, with no luck:

```
$ npm install babel-polyfill
~
├─┬ babel-polyfill@6.3.14
│ ├── babel-regenerator-runtime@6.3.13
│ ├── babel-runtime@5.8.34
│ └── core-js@1.2.6
└── slack-irc@3.7.1

$ ~/node_modules/.bin/slack-irc --config slackrelay_config.json
[Mon Jan 11 2016 18:27:06 GMT+0000 (GMT)] INFO Connecting...
~/node_modules/irc/lib/irc.js:751
                        throw err;
                              ^
TypeError: Cannot read property 'map' of undefined
    at Bot.sendToSlack (~/node_modules/slack-irc/dist/bot.js:260:59)
    at Client.emit (events.js:118:17)
    at Client.<anonymous> (~/node_modules/irc/lib/irc.js:519:22)
    at Client.emit (events.js:107:17)
    at iterator (~/node_modules/irc/lib/irc.js:748:26)
    at Array.forEach (native)
    at Socket.<anonymous> (~/node_modules/irc/lib/irc.js:743:15)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
```

This is, as before, on a Ubuntu 12.04 with:
```
$ nodejs -v
v0.12.9
$ npm -v
3.5.3
```

Any ideas about this?

**Comment by ekmartin** [comment]
I wrongly put `babel-polyfill` as a devDependency, while it should've been a normal dependency. [3.7.2](https://github.com/ekmartin/slack-irc/blob/master/CHANGELOG.md#372---2016-01-12) uses functions that are available in Node 0.10 and above instead of polyfills.

I haven't seen the other issue you're mentioning before though, would be awesome if you could create a separate issue for it (preferably with a stripped down config similar to the one you're using). Node 0.12 is quite an old version by the way, the latest release is version 5: https://github.com/nodesource/distributions#installation-instructions 

I don't think that's the problem here though, as I wasn't able to reproduce your issue using 0.12.

**Comment by nevik** [comment]
Thanks again for the quick reply! 

I'll test 3.7.2 tonight. 

From what I saw online, newer node versions cause issues on Ubuntu 12.04, so I didn't try updating further.

**Comment by ekmartin** [comment]
Sounds good!

**Comment by nevik** [comment]
Alright, this update now fixed the dependency issue. Thanks again :)

The second issue i ran into happened when the bot was successfully connected to both Slack and IRC, had joined the IRC channel(s) and someone sent a message on that IRC channel while the bot had not been invited to the corresponding Slack channel from the config file.

Crashing in this case isn't very nice, so this should be looked into. Want me to open another issue for this? (the bot itself is working for me now, so this isn't really affecting me anymore)

**Comment by ekmartin** [comment]
Thought that was covered already, but apparently the check wasn't thorough enough. Should be fixed with https://github.com/ekmartin/slack-irc/commit/4a34c649fdf11bd5108be57036f41b57e5f1c05a, so no need to create an issue. Thanks for the report!
