### ISSUE TITLE
IRC to private slack channel does not work

### ISSUE THREAD

**Issue by docjkl** [ekmartin/slack-irc#72]
Hi,

I have a private group in slack, 'drjkltest' and I am trying to send IRC notices to '#drjkltest'
I have invited the bot to the private channel on slack and it is present. 
I can send a message from slack to irc  but not from irc to slack. 

info: Tried to send a message to a channel the bot isn't in:  drjkltest

It works in public channels.  

Has something changed?

**Comment by ekmartin** [comment]
Hi! Seems like I broke this by introducing the `channel.is_member` check in 3.7.3, as node-slack-client groups don't have the `is_member` property. Should be fixed in [3.7.4](https://github.com/ekmartin/slack-irc/commit/117fbb1ad35363f30cbaa45ea0d2a57d5fc1745e).

Thanks for the report!

**Comment by avabinary** [comment]
hi, i'm getting a problem on the other end. slack messages aren't forwarded to the irc channel, but irc messages go through just fine.
