### ISSUE TITLE
Give Don a break. Username highlighting tweak.

### ISSUE THREAD

**Issue by Ibuprofen** [ekmartin/slack-irc#73]
I have a user in my slack with the name of `don`, unfortunately the user is notified any time someone writes `don't` due to the way the regex is setup in the `highlightUsername` function. 

I have a small code change which does not break the tests and allows don to get relief from the notifications. The regex will look for usernames with a colon or comma as part of the word, if not, they are not highlighted. This will still allow `username:` and `username, blah` but not `username's`.

If this is disired I will open a PR. What do you think? Thanks.

**Comment by ekmartin** [comment]
Agreed, definitely can't have that! A pull request would be most welcome. Maybe add dot, question mark and exclamation mark to the list of characters too?

**Comment by Ibuprofen** [comment]
Sure thing! https://github.com/ekmartin/slack-irc/pull/74

**Comment by ekmartin** [comment]
Released in [3.7.5](https://github.com/ekmartin/slack-irc/blob/master/CHANGELOG.md#375---2016-01-26) - thanks!
