### ISSUE TITLE
Avoid name-pinging people in IRC with the same username

### ISSUE THREAD

**Issue by laughinghan** [ekmartin/slack-irc#88]
Say `laughinghan` is in both Slack and IRC, it'd be nice to, when broadcasting from Slack to IRC, send a message of the form
```
<l aughinghan> message
```
(note the space after the first letter) to avoid name-pinging in IRC

Maybe I'm the only one with this problem since I'm in both

**Comment by ekmartin** [comment]
I've noticed the problem myself, but I'm not sure if this would be the way to go. Wouldn't it be simpler to just turn of highlighting for that specific IRC channel?

**Comment by laughinghan** [comment]
Oh you have? I've set my IRC client to ignore namepings by just the `<MathQuill_Slack>` nick (in Textual it's `/ignore`; apparently it's a common feature in IRC clients), which actually is what I want even for namepings in the body of the message because it's already pinging me in Slack which is my preferred channel anyway

But a built-in solution would be nice. Could we insert an invisible unicode character in the middle of the nickname? How is IRC's Unicode story?

**Comment by ekmartin** [comment]
I'm not completely sure, but I think it might be a bit hard to get right across everything from terminal clients like Irssi to stuff like IRCCloud. Could be worth testing though.

**Comment by ekmartin** [comment]
Closing this for now, might be worth investigating in the future - but I don't think it's necessary at the moment.
