### ISSUE TITLE
Reconnects

### ISSUE THREAD

**Issue by titusfortner** [ekmartin/slack-irc#95]
Right now I'm getting the error: `ERROR Last pong is too old:` and then my bot quits the IRC channel. 
For this to be a useful solution for our project, we need to be able to auto-reconnect.

**Comment by ekmartin** [comment]
Apparently node-irc defaults to a retry count of 0. I'll set it to something a bit higher. While waiting you can do so manually by adding `ircOptions` (which is passed directly to node-irc) in your slack-irc config:

```json
"ircOptions": {
  "retryCount": 5
}
```

**Comment by ekmartin** [comment]
3.7.8 has been released with a retry count of 10, hopefully this should solve the problem.
